<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Plan de pruebas" duration-ms="0" started-at="2018-02-19T17:30:03Z" finished-at="2018-02-19T17:30:03Z">
    <groups>
    </groups>
  </suite> <!-- Plan de pruebas -->
  <suite name="SuitePruebas" duration-ms="258" started-at="2018-02-19T17:30:02Z" finished-at="2018-02-19T17:30:02Z">
    <groups>
    </groups>
    <test name="Pruebas" duration-ms="258" started-at="2018-02-19T17:30:02Z" finished-at="2018-02-19T17:30:02Z">
      <class name="Aritmetica.Aritmetica.Parametros">
        <test-method status="PASS" signature="setUp()[pri:0, instance:Aritmetica.Aritmetica.Parametros@608bc8f8]" name="setUp" is-config="true" duration-ms="28" started-at="2018-02-19T11:30:02Z" finished-at="2018-02-19T11:30:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="ProbarDiv()[pri:0, instance:Aritmetica.Aritmetica.Parametros@608bc8f8]" name="ProbarDiv" duration-ms="100" started-at="2018-02-19T11:30:02Z" finished-at="2018-02-19T11:30:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [5.0] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [5.0] but found [6]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:167)
	at Aritmetica.Aritmetica.Parametros.ProbarDiv(Parametros.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProbarDiv -->
        <test-method status="PASS" signature="ProbarMulti()[pri:0, instance:Aritmetica.Aritmetica.Parametros@608bc8f8]" name="ProbarMulti" duration-ms="5" started-at="2018-02-19T11:30:02Z" finished-at="2018-02-19T11:30:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProbarMulti -->
        <test-method status="PASS" signature="ProbarResta()[pri:0, instance:Aritmetica.Aritmetica.Parametros@608bc8f8]" name="ProbarResta" duration-ms="16" started-at="2018-02-19T11:30:02Z" finished-at="2018-02-19T11:30:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProbarResta -->
        <test-method status="PASS" signature="ProbarSuma()[pri:0, instance:Aritmetica.Aritmetica.Parametros@608bc8f8]" name="ProbarSuma" duration-ms="9" started-at="2018-02-19T11:30:02Z" finished-at="2018-02-19T11:30:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProbarSuma -->
        <test-method status="PASS" signature="setOut()[pri:0, instance:Aritmetica.Aritmetica.Parametros@608bc8f8]" name="setOut" is-config="true" duration-ms="0" started-at="2018-02-19T11:30:02Z" finished-at="2018-02-19T11:30:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setOut -->
      </class> <!-- Aritmetica.Aritmetica.Parametros -->
    </test> <!-- Pruebas -->
  </suite> <!-- SuitePruebas -->
</testng-results>
